### ISSUE TITLE
Table that is paginated

### ISSUE THREAD

**Issue by alegbebomby** [2amigos/yii2-export-grid-button-widget#1]
this  plugin only export the  first  page it doesnt get the how table.   how can you   fix that.  if

**Comment by kinwing** [comment]
@alegbebomby  can you tell me how to use this widget , because this dosn't appear!

**Comment by tonydspaniard** [comment]
@alegbebomby @alegbebomby I am going to update everything and i am sorry i couldn't handle anything before.
