### ISSUE TITLE
Button doesnt not apper

### ISSUE THREAD

**Issue by FilipLukac** [2amigos/yii2-export-grid-button-widget#2]
Hello I've used 

``` php
<?= ButtonTableExport::widget(
                        [
                            'label' => 'Export Table',
                            'selector' => '#example', // any jQuery selector
                            'exportClientOptions' => [
                                'useDataUri' => true,
                                'url' => \yii\helpers\Url::to('user/download')
                            ]
                        ]
                    );?>
```

and button does not appear at all. (It doesnt echo the button )

**Comment by tonydspaniard** [comment]
@Chipsi have you checked your browser console? What is the result? What about the source code? Renders the HTML?

**Comment by tonydspaniard** [comment]
It seems that the Bootstrap API was updated. I have to check it. I am refactoring all extensions (http://yiiwheels.com). Will take a look on this one next.

**Comment by FilipLukac** [comment]
@tonydspaniard Yes, I've checked every possibility (I guess). It seems like a you code does not return the html button :)

**Comment by tonydspaniard** [comment]
Strange... We use it. Will revisit today.

**Comment by drama17** [comment]
Have the same issue. In browser console have see nothing (like the code does not exist)

**Comment by vicmonmena** [comment]
Hi!

Same issue! The button doesn't appeared and the console say nothing.

Any fix?

Thx!

**Comment by kinwing** [comment]
@vicmonmena can you use it normally?

**Comment by kinwing** [comment]
@FilipLukac can you use it normally now?

**Comment by FilipLukac** [comment]
@Kinwing sorry, I actually do not develop any webapplication under Yii2

**Comment by bitsnitin** [comment]
Hi, I am also facing same issue! The button doesn't appeared and the console say nothing, also when I inspect the code JQuery Code is generated but html for button is not rendered

**Comment by akomarovskih** [comment]
Hi, export dropdown is not echo in your code! Your examples is not working.

**Comment by tonydspaniard** [comment]
Sorry guys for the delay... I promise will fix everything.
